---
- name: Install melodi
  hosts: all

  tasks:
  - name: install apache
    package:
      name: httpd
      state: present

  - name: start httpd
    systemd:
      name: httpd
      state: started
      enabled: yes

  - name: pull melodi
    git:
      repo: https://github.com/ikambarov/melodi.git
      version: master
      dest: /var/www/html/

  - name: recursively change ownership of a directory
    file:
      path: /var/www/html
      state: directory
      recurse: yes
      owner: apache
      group: apache

